# fly.toml app configuration file generated for clarabot on 2023-06-21T00:52:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "clarabot"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

[mount]
  source = "clarastorage"
  destination = "/mnt"